### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by pperliti** [citusdata/django-multitenant#131]
Hi, does this package also support Oracle DB or is just limited to Postgres?

**Comment by s4ke** [comment]
Haven't tried this myself, but from what I know about the code, this could just as well work for Oracle. I'd say it would be worth a try :)

**Comment by pperliti** [comment]
Thank you, I'll give it a try. I need to covert my Django app into a multi-tenant app (right now I have multiple installations, but soon it's going to be unmantainable) and I read a lot about "one DB w/ isolated schemas" vs "one DB w/ shared schema". Each approach one has its pros and cons, so I thought to try both and see which one fits best in my case (from 10 to 20 tenants, but I also need to gather global statistics). 
I found several packages using "one DB w/ isolated schemas" but in the end they are limited to Postgres ...and it's ok (Postgres is great) nonetheless I don't feel so much confident to be bounded to one specific DB architecture (what if I need to migrate to Oracle?).

**Comment by gurkanindibay** [comment]
Hi,
We haven't tested the application on Oracle. There are unit tests all are working on Postgres and Citus Cluster. Without executing tests, we can not guarantee Oracle support. Unfortunately, since the focus of this project is Postgres and Citus, there will not be a test or feature for Oracle support  in the future.
